### PR TITLE
Add support for multiple VPN providers such as TorGuard, fix OVPN copy path in compose file. Update docs.

### PR DESCRIPTION
**Pull request by leewc**
Hi there, 

I saw your [Reddit thread](https://www.reddit.com/r/PleX/comments/8alh2h/docker_based_htpc_standup_for_plex_deluge_vpn/) (long time lurker of Reddit) and was looking to repurpose my old laptop as a 21st century media center with all the bells and whistles of Docker, decided to use your set up as I use Deluge too! Thought I'd contribute back while trying to set it up. Thank you for your work!

Changes made: 
- Added TorGuard configs (binhex's Deluge defaults to the first one)
  - Let me know if you prefer not to add config files, I'm following what https://github.com/haugene/docker-transmission-openvpn did.
- Rename PIA variables to VPN 
- Fix mapping of `ovpn` path to ensure VPN configs are correctly copied over

Testing done: 

1. Ran `docker-compose up arch-delugevpn` to view logs, output attached here: 
[deluge-up.txt](https://github.com/phikai/htpc-docker-standup/files/2053171/deluge-up.txt)
2. On separate terminal:

```
docker exec -it <container-id> bash
deluge-console -c /config
```

Then copied magnet from https://torguard.net/checkmytorrentipaddress.php and checked the IP address. IP address defaults to Australia indicating set up does not leak IP.

Output

```
Deluge 1.3.15 Console - localclient@127.0.0.1:58846  

>>> add magnet:?xt=urn:btih:466d7d0ac472ffce171029a928646643a56e36f7&dn=checkmy
iptorrent&tr=http%3A%2F%2F34.204.227.31%2Fcheckmytorrentipaddress.php
Torrent added!                                                                 
* TorrentStateChanged: Paused None (466d7d0ac472ffce171029a928646643a56e36f7)  
* TorrentStateChanged: Downloading None (466d7d0ac472ffce171029a928646643a56e36
f7)                                                                            
* TorrentAdded: checkmyiptorrent (466d7d0ac472ffce171029a928646643a56e36f7)    
C: 0 (200) D: 0.0 KiB U: 0.0 KiB DHT: 308           
```

Additional Note: Could you attach your './nginx-proxy/etc/nginx/vhost.d` and './nginx-proxy/usr/share/nginx/html` ? Or at least a sample. At it's initial state (checkout, edit `.env` and `docker-compose up` the cluster doesn't start up successfully.

### CODE REVIEW

**Comment by phikai** [comment]
Thanks for this... let me see what it would take to drop this in, but it seems like a reasonable add.

**Comment by leewc** [comment]
Awesome, thanks for the reply and taking a look! Yep I figured since I'm trying to set one up and am benefitting for your Docker Compose as a starter I might as well try and contribute back! 

Ideally I hope we reach a state where the cluster can start up out of the box after editing variables in  `.env`! Trying to get the reverse proxy working now.

**Comment by phikai** [comment]
Thanks again!

**Comment by leewc** [comment]
Most welcome! Thanks for merging and giving me a jumpstart with setting this up! Appreciate it.

**Pull request merged**
